const API_KEY='hros.api.url';const STORAGE_KEY='hros.snapshot.v1';const HISTORY_KEY='hros.history.v1';
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const api=()=>String(localStorage.getItem(API_KEY)||window.__HROS_CONFIG__?.apiUrl||'').replace(/\/$/,'');
const readLocal=()=>JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');
const writeLocal=s=>{s.meta={...(s.meta||{}),version:'1.0.0',schemaVersion:'1.0.0',updatedAt:new Date().toISOString()};localStorage.setItem(STORAGE_KEY,JSON.stringify(s));};
const history=()=>JSON.parse(localStorage.getItem(HISTORY_KEY)||'[]');
const addHistory=(kind,id,action,before,after)=>{const h=history();h.unshift({id:crypto.randomUUID(),kind,entityId:id,action,at:new Date().toISOString(),before,after});localStorage.setItem(HISTORY_KEY,JSON.stringify(h.slice(0,1000)));};
async function request(path,options={}){const r=await fetch(`${api()}${path}`,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});const data=await r.json().catch(()=>null);if(!r.ok)throw new Error(data?.detail||`HTTP ${r.status}`);return data;}
async function snapshot(){return api()?request('/snapshot'):readLocal();}
async function updatePerson(id,payload){if(api())return request(`/people/${id}`,{method:'PATCH',body:JSON.stringify(payload)});const s=readLocal(),i=s.people.findIndex(x=>x.id===id);if(i<0)throw new Error('Человек не найден');const before=structuredClone(s.people[i]);s.people[i]={...s.people[i],...payload,version:(s.people[i].version||1)+1,updatedAt:new Date().toISOString()};addHistory('person',id,'update',before,s.people[i]);writeLocal(s);return s.people[i];}
async function deletePerson(id){if(api())return request(`/people/${id}`,{method:'DELETE'});const s=readLocal(),p=s.people.find(x=>x.id===id);if(!p)throw new Error('Человек не найден');if(p.isSelf)throw new Error('Нельзя удалить центральный профиль');addHistory('person',id,'delete',p,null);s.people=s.people.filter(x=>x.id!==id);s.relationships=s.relationships.filter(x=>x.sourceId!==id&&x.targetId!==id);s.moments=s.moments.map(m=>({...m,participantIds:(m.participantIds||[]).filter(x=>x!==id)}));s.records=(s.records||[]).map(r=>({...r,subjectIds:(r.subjectIds||[]).filter(x=>x!==id),perspectiveOwnerId:r.perspectiveOwnerId===id?null:r.perspectiveOwnerId}));writeLocal(s);return {ok:true};}
async function finalizePerson(id){return updatePerson(id,{status:'finalized',finalizedAt:new Date().toISOString()});}
async function saveRelationship(payload,id){if(api())return id?request(`/relationships/${id}`,{method:'PATCH',body:JSON.stringify(payload)}):request('/relationships',{method:'POST',body:JSON.stringify(payload)});const s=readLocal();if(id){const i=s.relationships.findIndex(x=>x.id===id),before=structuredClone(s.relationships[i]);s.relationships[i]={...s.relationships[i],...payload,version:(s.relationships[i].version||1)+1,updatedAt:new Date().toISOString()};addHistory('relationship',id,'update',before,s.relationships[i]);}else{s.relationships.push({id:`rel-${crypto.randomUUID()}`,...payload,status:'observed',confidence:1,version:1,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),source:{kind:'user',label:'Редактор HROS v1'}});}writeLocal(s);}
async function deleteRelationship(id){if(api())return request(`/relationships/${id}`,{method:'DELETE'});const s=readLocal(),r=s.relationships.find(x=>x.id===id);addHistory('relationship',id,'delete',r,null);s.relationships=s.relationships.filter(x=>x.id!==id);s.records=(s.records||[]).map(x=>({...x,relationshipIds:(x.relationshipIds||[]).filter(y=>y!==id)}));writeLocal(s);}
function ensureDialog(){if(document.querySelector('#v03Dialog'))return;document.body.insertAdjacentHTML('beforeend',`<dialog id="v03Dialog" class="modal v03-modal"><form id="v03Form"><header><div><span class="eyebrow">HROS v1</span><h2 id="v03Title">Редактор</h2></div><button type="button" class="icon-button" data-v03-close>×</button></header><div id="v03Body" class="form-grid"></div><footer><button type="button" class="secondary" data-v03-close>Отмена</button><button class="primary" type="submit">Сохранить новую версию</button></footer></form></dialog>`);document.querySelectorAll('[data-v03-close]').forEach(b=>b.onclick=()=>document.querySelector('#v03Dialog').close());}
async function editPerson(id){ensureDialog();const s=await snapshot(),p=s.people.find(x=>x.id===id);const d=document.querySelector('#v03Dialog'),f=document.querySelector('#v03Form');document.querySelector('#v03Title').textContent=`Редактировать: ${p.name}`;document.querySelector('#v03Body').innerHTML=`<label>Имя<input name="name" required value="${esc(p.name)}"></label><label>Роль<input name="role" value="${esc(p.role)}"></label><label>Категория<select name="type">${['family','friend','work','project','legacy','other'].map(x=>`<option ${x===p.type?'selected':''}>${x}</option>`).join('')}</select></label><label>Значимость узла<input name="strength" type="number" min="0" max="100" value="${p.strength}"></label><label>Статус<select name="status">${['draft','observed','hypothesis','confirmed','disputed','finalized','archived'].map(x=>`<option ${x===p.status?'selected':''}>${x}</option>`).join('')}</select></label><label>Уверенность<input name="confidence" type="number" min="0" max="1" step="0.05" value="${p.confidence??1}"></label><label class="wide">Краткое описание<textarea name="summary" rows="5">${esc(p.summary)}</textarea></label>`;f.onsubmit=async e=>{e.preventDefault();const x=Object.fromEntries(new FormData(f));x.strength=Number(x.strength);x.confidence=Number(x.confidence);await updatePerson(id,x);d.close();location.reload();};d.showModal();}
async function relationshipManager(){ensureDialog();const s=await snapshot(),d=document.querySelector('#v03Dialog'),f=document.querySelector('#v03Form');document.querySelector('#v03Title').textContent='Редактор отношений';document.querySelector('#v03Body').innerHTML=`<label>От кого<select name="sourceId">${s.people.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select></label><label>К кому<select name="targetId">${s.people.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select></label><label>Название<input name="label" required value="Связь"></label><label>Тип<input name="type" value="personal"></label><label>Интенсивность<input name="strength" type="number" min="0" max="100" value="70"></label><label class="wide">Смысл<textarea name="meaning"></textarea></label><p class="wide muted">Состояния доверия, безопасности и взаимности фиксируются отдельно в разделе «Знания», а не сводятся к одному числу.</p><div class="wide relation-admin">${s.relationships.map(r=>`<article><b>${esc(s.people.find(p=>p.id===r.sourceId)?.name)} → ${esc(s.people.find(p=>p.id===r.targetId)?.name)}</b><span>${esc(r.label)} · ${r.strength}</span><button type="button" class="danger" data-delete-rel="${r.id}">Удалить</button></article>`).join('')}</div>`;document.querySelectorAll('[data-delete-rel]').forEach(b=>b.onclick=async()=>{if(confirm('Удалить связь?')){await deleteRelationship(b.dataset.deleteRel);location.reload();}});f.onsubmit=async e=>{e.preventDefault();const x=Object.fromEntries(new FormData(f));x.strength=Number(x.strength);if(x.sourceId===x.targetId)throw new Error('Нужны разные узлы');await saveRelationship(x);d.close();location.reload();};d.showModal();}
function historyPanel(){ensureDialog();const h=history();document.querySelector('#v03Title').textContent='История версий';document.querySelector('#v03Body').innerHTML=`<div class="wide revision-list">${h.length?h.map(x=>`<article><b>${esc(x.kind)} · ${esc(x.action)}</b><span>${new Date(x.at).toLocaleString('ru-RU')} · ${esc(x.entityId)}</span></article>`).join(''):'История появится после первого изменения.'}</div>`;document.querySelector('#v03Form').onsubmit=e=>e.preventDefault();document.querySelector('#v03Dialog').showModal();}
async function enhance(){const people=document.querySelectorAll('[data-open-person]');people.forEach(open=>{const card=open.closest('.entity-card');if(!card||card.querySelector('.v03-actions'))return;const id=open.dataset.openPerson;const isSelf=id==='person-mikhail';card.insertAdjacentHTML('beforeend',`<div class="v03-actions"><button class="secondary" data-edit-person="${id}">Изменить</button><button class="primary" data-finalize-person="${id}">Финализировать</button>${isSelf?'':`<button class="danger" data-delete-person="${id}">Удалить</button>`}</div>`);});document.querySelectorAll('[data-edit-person]').forEach(b=>b.onclick=()=>editPerson(b.dataset.editPerson));document.querySelectorAll('[data-finalize-person]').forEach(b=>b.onclick=async()=>{await finalizePerson(b.dataset.finalizePerson);location.reload();});document.querySelectorAll('[data-delete-person]').forEach(b=>b.onclick=async()=>{if(confirm('Удалить человека, его связи и участие в моментах?')){await deletePerson(b.dataset.deletePerson);location.reload();}});const header=document.querySelector('.top-actions');if(header&&!header.querySelector('[data-relations]'))header.insertAdjacentHTML('afterbegin','<button class="secondary" data-history>Версии</button><button class="secondary" data-relations>Связи</button>');document.querySelector('[data-relations]')?.addEventListener('click',relationshipManager,{once:true});document.querySelector('[data-history]')?.addEventListener('click',historyPanel,{once:true});const brand=document.querySelector('.brand small');const version='Human Relationship Operating System · v1.0';if(brand&&brand.textContent!==version)brand.textContent=version;}
ensureDialog();let scheduled=false;const scheduleEnhance=()=>{if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;enhance().catch(console.error);});};new MutationObserver(scheduleEnhance).observe(document.querySelector('#app'),{childList:true,subtree:true});scheduleEnhance();
