export const K={api:'hros.api.url',data:'hros.snapshot.v1',hist:'hros.history.v1',events:'hros.diagnostics.v1',view:'hros.return.view'};
export const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
export const now=()=>new Date().toISOString();
const configuredApi=()=>String(localStorage.getItem(K.api)||window.__HROS_CONFIG__?.apiUrl||'').replace(/\/$/,'');
const api=()=>document.querySelector('#storageMode')?.classList.contains('api')?configuredApi():'';
const read=(k,f)=>JSON.parse(localStorage.getItem(k)||f);
export const record=(level,action,details={})=>{const a=read(K.events,'[]');a.unshift({id:crypto.randomUUID(),at:now(),level,action,details});localStorage.setItem(K.events,JSON.stringify(a.slice(0,200)));};
export const norm=m=>({...m,participantIds:Array.isArray(m?.participantIds)?m.participantIds:[],emotions:Array.isArray(m?.emotions)?m.emotions:[],relationshipEffect:{closeness:0,trust:0,tension:0,...(m?.relationshipEffect||{})},details:{meaning:'',place:'',tags:[],attachments:[],...(m?.details||{})},source:{kind:'user',label:'Добавлено пользователем',...(m?.source||{})}});
async function req(path,o={}){const t=performance.now(),r=await fetch(api()+path,{...o,headers:{'Content-Type':'application/json',...(o.headers||{})}}),x=await r.json().catch(()=>null);record(r.ok?'info':'error','moment.api',{path,status:r.status,ms:Math.round(performance.now()-t)});if(!r.ok)throw Error(x?.detail||`HTTP ${r.status}`);return x;}
export async function snapshot(){const s=api()?await req('/snapshot'):read(K.data,'null');if(!s)throw Error('Snapshot HROS v1 не найден');s.moments=(s.moments||[]).map(norm);return s;}
function write(s,a){s.meta={...(s.meta||{}),version:'1.0.0',schemaVersion:'1.0.0',updatedAt:now(),mode:'local'};localStorage.setItem(K.data,JSON.stringify(s));record('info',a,{moments:s.moments.length});}
function history(id,action,before,after){const h=read(K.hist,'[]');h.unshift({id:crypto.randomUUID(),kind:'moment',entityId:id,action,at:now(),before,after});localStorage.setItem(K.hist,JSON.stringify(h.slice(0,1000)));}
function validate(p,s){if(!p.title)throw Error('Название обязательно');if(!p.date)throw Error('Укажите дату');const ids=new Set(s.people.map(x=>x.id));if(p.participantIds.some(id=>!ids.has(id)))throw Error('Неизвестный участник');for(const v of Object.values(p.relationshipEffect))if(v<-1||v>1)throw Error('Влияние должно быть от -1 до 1');}
export async function saveMoment(id,p){const s=await snapshot();validate(p,s);if(api())return req(id?`/moments/${id}`:'/moments',{method:id?'PATCH':'POST',body:JSON.stringify(p)});if(id){const i=s.moments.findIndex(x=>x.id===id);if(i<0)throw Error('Момент не найден');const b=structuredClone(s.moments[i]);s.moments[i]=norm({...s.moments[i],...p,version:(s.moments[i].version||1)+1,updatedAt:now()});history(id,p.status==='finalized'?'finalize':'update',b,s.moments[i]);write(s,'moment.update');return s.moments[i];}const x=norm({id:`moment-${crypto.randomUUID()}`,...p,version:1,createdAt:now(),updatedAt:now()});s.moments.push(x);history(x.id,'create',null,x);write(s,'moment.create');return x;}
export async function deleteMoment(id){if(api())return req(`/moments/${id}`,{method:'DELETE'});const s=await snapshot(),x=s.moments.find(m=>m.id===id);if(!x)throw Error('Момент не найден');history(id,'delete',x,null);s.moments=s.moments.filter(m=>m.id!==id);s.records=(s.records||[]).map(r=>({...r,momentIds:(r.momentIds||[]).filter(x=>x!==id)}));write(s,'moment.delete');}
export async function revisions(id){return api()?req(`/moment/${id}/revisions`):read(K.hist,'[]').filter(x=>x.kind==='moment'&&x.entityId===id);}
